- hosts: localhost
  tasks:
    - name: Check install nginx
      shell: dpkg -l | grep nginx
      register: nginx_status

    - name: Message about install nginx
      debug:
        msg: "Nginx already installed"
      when: nginx_status.rc == 0
  vars:
    ansible_verbosity: 0